### ISSUE TITLE
Slappygig, if you're reading this...

### ISSUE THREAD

**Issue by Ao28th28** [Ao28th28/Ao28th28.github.io#2]
XPMUser.github.io and this site are ready, but they are considered in beta.

**Comment by slappygig** [comment]
Can you add versions yourself like daboss7173 does? I am just wondering

**Comment by Ao28th28** [comment]
Can you create a pull request?

**Comment by Ao28th28** [comment]
https://slappygig.github.io/oldprodigy/1-11-0/ Doesn't boot up for me, use daboss7173's 1.11.0 or my 1.11.0 to update it.

**Comment by Ao28th28** [comment]
> Can you add versions yourself like daboss7173 does? I am just wondering

Yes/Maybe

**Comment by slappygig** [comment]
I'm not on pc I'm on mobile so I can't fix prodigy clover right now

**Comment by Ao28th28** [comment]
https://www.youtube.com/channel/UCqV2C-s63zSZszqKWQ1c_Vw/community?lb=Ugkx2OChJd1rjf96wWgfjnKTNhuQuT4Tm3ut Get your account on new prodigy signed up to battle Mr. Inquiry.

**Comment by Ao28th28** [comment]
> I'm not on pc I'm on mobile so I can't fix prodigy clover right now

https://www.bestbuy.ca/en-ca/search?search=windows+10+home I found some pcs that you can buy.

**Comment by Ao28th28** [comment]
Is your 1.11.0's Bannard fixed before 1.11.0 couldn't boot up?

**Comment by Ao28th28** [comment]
Too bad I don't have the scripts for the actual 1.3.1 either.

**Comment by Ao28th28** [comment]
I hope 2012 Prodigy comes soon.

**Comment by Ao28th28** [comment]
> I'm not on pc I'm on mobile so I can't fix prodigy clover right now

When you're on pc, can you fix 1.11.0 for your site?

**Comment by Ao28th28** [comment]
2-20-0 is ready!

**Comment by Ao28th28** [comment]
xpmuser.github.io is fixed except I don't have the button picture files for all versions.

**Comment by Ao28th28** [comment]
Toontown music for xpmuser.github.io's 1.11.0 is coming soon.
