### ISSUE TITLE
Add the toontown music back in 1.11.0

### ISSUE THREAD

**Issue by slappygig** [Ao28th28/Ao28th28.github.io#8]
What would you like to add: 
Bring back the toontown win  and fight theme in 1.11.0

How would you want it to be implemented:
Add the toontown music back in version 1.11.0

Any additional context:

**Comment by Ao28th28** [comment]
Go to xpmuser.github.io, toontown will be back in ao28th28.github.io soon.

**Comment by Ao28th28** [comment]
Toontown songs are now back in [ao28th28.github.io](url)

**Comment by Ao28th28** [comment]
I'm still working on fixing the survey for 2-30-0.
